name: Build Plugin

on: 
  push: 
    branches:
      - master
  pull_request:

  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore AutomateBitlockerPlugin.sln

      - name: Install .NET Framework 4.5.2 Developer Pack
        run: choco install netfx-4.5.2-devpack -y

      - name: Locate required Windows assemblies
        shell: powershell
        run: |
          Write-Host "=== Group Policy ==="
          Get-ChildItem "C:\" -Recurse -ErrorAction SilentlyContinue `
          -Filter "Microsoft.GroupPolicy.Management.dll" | 
          Select-Object -ExpandProperty FullName

          Write-Host "=== Bitlocker ==="
          Get-ChildItem "C:\Windows\System32\WindowsPowerShell\v1.0\Modules" `
          -Recurse -ErrorAction SilentlyContinue `
          -Filter "Microsoft.BitLocker.Structures.dll" | 
          Select-Object -ExpandProperty FullName
          
      - name: Build solution
        run: msbuild AutomateBitlockerPlugin\AutomateBitlockerPlugin.csproj /p:Configuration=Release

      - name: Upload compiled plugin
        uses: actions/upload-artifact@v4
        with:
          name: AutomateBitlockerPlugin
          path: AutomateBitlockerPlugin/bin/Release/
